log syslog all;

router id 10.69.1.90;

protocol device {
  scan time 10;
}

protocol kernel {
  export all;
  scan time 15;
}

protocol static {
  import all;
}

protocol ospf MyOSPF {
  ipv4 {
    export filter {
      ospf_metric1 = 100;
      accept;
    };
  };
  area 0.0.0.0 {
    interface "ether3" {
      cost 1;
      hello 15;
      priority 100;
      retransmit 7;
    };
    interface "vlan10" {
      cost 1;
      hello 15;
      priority 100;
      retransmit 7;
    };
  };
}

